# Generated by Django 5.0.6 on 2025-03-13 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(help_text='Recommended size: 200x100 pixels. Use transparent background if possible.', upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('website', models.URLField(blank=True, help_text='Optional link to partner website', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Partner',
                'verbose_name_plural': 'Brand Partners',
                'ordering': ['order'],
            },
        ),
    ]
